name: Cleanup_And_Restore

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      job_selection:
        type: choice
        options:
          - replica-create
          - delete-db
          - all
        description: select all or specific tasks to run
      switch_to_region:
        type: choice
        description: provide ur choice
        options: 
        - us-west
        - us-east

  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  REPLICA_CREATE_US_EAST:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    needs: [DB_DELETE_US_EAST]
    if: |
      (contains(inputs.switch_to_region, 'us-east') && contains(inputs.job_selection, 'replica-create')) ||
      (contains(inputs.switch_to_region, 'us-east') && contains(inputs.job_selection, 'all'))
    env:
      PROJECT_ID: 'grand-thought-365806'
    steps:
      - name: Set up gcloud Cloud SDK environment
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/13793097680/locations/global/workloadIdentityPools/cleanup/providers/github-provider-2'
          service_account: 'jenkins-gke-dr-test@grand-thought-365806.iam.gserviceaccount.com'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: 'Use gcloud CLI'
        run: |
          gcloud info
          gcloud version
          gcloud sql instances create geodb-replica --master-instance-name=geodb --zone=us-east1-b --replica-type=READ --replication=synchronous --deletion-protection --no-assign-ip --network=projects/grand-thought-365806/global/networks/default --quiet 
  DB_DELETE_US_EAST:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    if: |
      (contains(inputs.switch_to_region, 'us-east') && contains(inputs.job_selection, 'delete-db')) ||
      (contains(inputs.switch_to_region, 'us-east') && contains(inputs.job_selection, 'all'))
    env:
      PROJECT_ID: 'grand-thought-365806'
    steps:
      - name: Set up gcloud Cloud SDK environment
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/13793097680/locations/global/workloadIdentityPools/cleanup/providers/github-provider-2'
          service_account: 'jenkins-gke-dr-test@grand-thought-365806.iam.gserviceaccount.com'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: 'Use gcloud CLI'
        run: |
          gcloud info
          gcloud version
          gcloud sql instances patch geodb-replica --no-deletion-protection # disable deletion protection
          gcloud sql instances delete geodb-replica --quiet
  REPLICA_CREATE_US_WEST:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    needs: [DB_DELETE_US_WEST]
    if: |
      (contains(inputs.switch_to_region, 'us-west') && contains(inputs.job_selection, 'replica-create')) ||
      (contains(inputs.switch_to_region, 'us-west') && contains(inputs.job_selection, 'all'))
    env:
      PROJECT_ID: 'grand-thought-365806'
    steps:
      - name: Set up gcloud Cloud SDK environment
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/13793097680/locations/global/workloadIdentityPools/cleanup/providers/github-provider-2'
          service_account: 'jenkins-gke-dr-test@grand-thought-365806.iam.gserviceaccount.com'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: 'Use gcloud CLI'
        run: |
          gcloud info
          gcloud version
          gcloud sql instances create geodb --master-instance-name=geodb-replica --zone=us-west1-b --replica-type=READ --replication=synchronous --deletion-protection --no-assign-ip --network=projects/grand-thought-365806/global/networks/default --quiet
  DB_DELETE_US_WEST:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    if: |
      (contains(inputs.switch_to_region, 'us-west') && contains(inputs.job_selection, 'delete-db')) ||
      (contains(inputs.switch_to_region, 'us-west') && contains(inputs.job_selection, 'all'))
    env:
      PROJECT_ID: 'grand-thought-365806'
    steps:
      - name: Set up gcloud Cloud SDK environment
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/13793097680/locations/global/workloadIdentityPools/cleanup/providers/github-provider-2'
          service_account: 'jenkins-gke-dr-test@grand-thought-365806.iam.gserviceaccount.com'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: 'Use gcloud CLI'
        run: |
          gcloud sql instances patch geodb --no-deletion-protection # disable deletion protection
          gcloud sql instances delete geodb --quiet
          
